version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ns-db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: ns-app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: ["air", "-c", ".air.toml"] 